[options]
addons_path = /etc/odoo/addons/core,/etc/odoo/addons/custom,/etc/odoo/addons/enterprise,/usr/lib/python3/dist-packages/odoo/addons
list_db = False
proxy_mode = True
server_wide_modules = web_enterprise
workers = 2
max_cron_threads = 1
longpolling_port = 8072
